var EA_API='https://script.google.com/macros/s/AKfycbyfr1k04IqvPSHND5I47ZowM8EAUmBuFR4pKJVWDdsB0ZCr4pMrCLxFME1v70aLbyWo/exec';
var EA_TRACKER={API_URL:EA_API,initialized:false,init:function(page){if(this.initialized)return;this.initialized=true;this.page=page||window.location.pathname;this.fingerprint=this.getFingerprint();var self=this;this.getIP().then(function(ip){self.ip=ip;self.send()});this.send()},getFingerprint:function(){var c=document.createElement('canvas');c.width=200;c.height=50;var t=c.getContext('2d');t.textBaseline='top';t.font='14px Arial';t.fillStyle='#f60';t.fillRect(125,1,62,20);t.fillStyle='#069';t.fillText('EA'+navigator.userAgent.length,2,15);t.fillStyle='rgba(102,204,0,0.7)';t.fillText('ExpressAirways',4,17);var n=c.toDataURL();var r='';try{var gl=document.createElement('canvas').getContext('webgl');if(gl){var ext=gl.getExtension('WEBGL_debug_renderer_info');if(ext)r=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)+'|'+gl.getParameter(ext.UNMASKED_VENDOR_WEBGL)}}catch(e){}var a=window.screen.width+'x'+window.screen.height+'x'+window.screen.colorDepth;var tz=Intl.DateTimeFormat().resolvedOptions().timeZone;var lang=navigator.language;var ua=navigator.userAgent;var s=[n,r,a,tz,lang,ua].join('|||');var h=0;for(var i=0;i<s.length;i++){var c2=s.charCodeAt(i);h=(h<<5)-h+c2;h|=0}return Math.abs(h).toString(16)},getIP:function(){return fetch('https://api.ipify.org?format=json',{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){return d.ip}).catch(function(){return''})},send:function(){var params={action:'audit.event',event:'pageview',page:this.page,fingerprint:this.fingerprint,ip:this.ip,ua:navigator.userAgent,screen:window.screen.width+'x'+window.screen.height,tz:Intl.DateTimeFormat().resolvedOptions().timeZone,lang:navigator.language};var qs=Object.entries(params).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');fetch(EA_API+'?'+qs+'&t='+Date.now(),{mode:'no-cors'}).catch(function(){})}};
var EA_AUTH={KEY:'ea_session',getUser:function(){try{var raw=localStorage.getItem(this.KEY);if(!raw)return null;var data=JSON.parse(raw);if(data&&data.user&&data.expires>Date.now())return data.user;if(data&&data.user)localStorage.removeItem(this.KEY);return null}catch(e){return null}},setUser:function(user){if(!user){localStorage.removeItem(this.KEY);return}var data={user:user,expires:Date.now()+604800000};localStorage.setItem(this.KEY,JSON.stringify(data))},logout:function(){localStorage.removeItem(this.KEY);this._notify(null)},_listeners:[],onChange:function(fn){this._listeners.push(fn)},_notify:function(user){for(var i=0;i<this._listeners.length;i++){try{this._listeners[i](user)}catch(e){}}}};
window.addEventListener('storage',function(e){if(e.key===EA_AUTH.KEY){try{var data=JSON.parse(e.newValue);EA_AUTH._notify(data?data.user:null)}catch(ex){EA_AUTH._notify(null)}}});
function Toast(type,message){var container=document.getElementById('toastContainer');if(!container)return;var icons={success:'\u2713',error:'\u2715',warning:'\u26A0',info:'\u2139'};var t=document.createElement('div');t.className='toast '+type;t.innerHTML='<span>'+(icons[type]||'')+'</span><span>'+message+'</span>';container.appendChild(t);var dur=type==='error'?10000:type==='success'?8000:6000;setTimeout(function(){t.style.animation='toastOut 0.3s ease forwards';setTimeout(function(){t.remove()},300)},dur)}
function $(id){return document.getElementById(id)}
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function show(el){if(el)el.classList.remove('hidden')}
function hide(el){if(el)el.classList.add('hidden')}
function qs(s){return document.querySelector(s)}
function qsa(s){return document.querySelectorAll(s)}
function btnLoading(el){if(!el)return;if(el.dataset._orig===undefined)el.dataset._orig=el.innerHTML;el.classList.add('loading');el.disabled=true}
function btnReset(el){if(!el)return;el.classList.remove('loading');el.disabled=false}
async function api(action,extra){var p={action:action};if(extra)for(var k in extra)p[k]=extra[k];var qs2=Object.entries(p).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');try{var c=new AbortController();var t=setTimeout(function(){c.abort()},15000);var r=await fetch(EA_API+'?'+qs2+'&t='+Date.now(),{cache:'no-store',signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}catch(e){console.error('EA API Error:',e);return null}}
function auditEvent(eventType,detail){try{var params={action:'audit.event',event:eventType,page:window.location.pathname,fingerprint:EA_TRACKER.fingerprint,detail:detail||'',user:currentUser?currentUser.email:''};var qs3=Object.entries(params).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');fetch(EA_API+'?'+qs3+'&t='+Date.now(),{mode:'no-cors'}).catch(function(e){console.error('Audit failed:',e)})}catch(e){console.error('Audit error:',e)}}
var currentUser=null;
var allKeys=[];
var allEndpoints=[];
var endpointsCache=[];
function updateDevAuthUI(){if(currentUser){hide($('loginwall'));show($('userMenu'));show($('logoutBtn'));$('avatarInitials').textContent=(currentUser.name||'U').charAt(0).toUpperCase();$('dropdownName').textContent=currentUser.name||'Developer';$('dropdownEmail').textContent=currentUser.email||'';loadKeys();loadEndpoints()}else{show($('loginwall'));hide($('userMenu'));hide($('logoutBtn'));$('keysTableContainer').innerHTML='<p style="color:var(--text-muted);text-align:center;padding:20px">Sign in to view your API keys.</p>'}}
async function login(email,pw){btnLoading(qs('#loginForm button[type="submit"]'));var d=await api('login',{email:email,password:pw});btnReset(qs('#loginForm button[type="submit"]'));if(d&&d.success){currentUser=d.user;EA_AUTH.setUser(d.user);updateDevAuthUI();Toast('success','Welcome, '+d.user.name);auditEvent('dev_login',email)}else{Toast('error',d&&d.message?d.message:'Login failed')}}
async function register(name,email,pw){btnLoading(qs('#registerForm button[type="submit"]'));var d=await api('signup',{fullName:name,email:email,password:pw});btnReset(qs('#registerForm button[type="submit"]'));if(d&&d.success){Toast('success','Account created. Please sign in.');switchAuthTab('login')}else{Toast('error',d&&d.message?d.message:'Registration failed')}}
function logoutUser(){currentUser=null;EA_AUTH.logout();updateDevAuthUI();Toast('info','Signed out');auditEvent('dev_logout','')}
function switchAuthTab(tab){qsa('.auth-tab').forEach(function(t){t.classList.toggle('active',t.dataset.tab===tab)});hide($('loginForm'));hide($('registerForm'));show(tab==='login'?$('loginForm'):$('registerForm'))}
function switchDevTab(tab){qsa('#devTabs .tab').forEach(function(t){t.classList.toggle('active',t.dataset.tab===tab)});hide($('tabDocs'));hide($('tabKeys'));hide($('tabExplorer'));show($('tab'+tab.charAt(0).toUpperCase()+tab.slice(1)));auditEvent('dev_tab',tab)}
async function loadEndpoints(){if(!currentUser)return;var d=await api('dev.listEndpoints',{});if(d&&d.success&&d.endpoints){endpointsCache=d.endpoints;renderEndpoints(d.endpoints)}else{document.getElementById('endpointsList').innerHTML='<p style="color:var(--text-muted);text-align:center;padding:20px">Unable to load API endpoints. Please try again later.</p>';endpointsCache=[]}}
function renderEndpoints(endpoints){if(!endpoints||endpoints.length===0){$('endpointsList').innerHTML='<p style="color:var(--text-muted);text-align:center;padding:20px">No endpoints available.</p>';return}var html='';endpoints.forEach(function(ep){var name=ep.name||ep.action||ep.endpoint||'Unknown';var method=(ep.method||'GET').toUpperCase();var desc=ep.description||ep.desc||ep.Description||'';var methodClass=method==='GET'?'method-get':'method-post';html+='<div class="endpoint-card"><div style="display:flex;align-items:center;gap:10px;margin-bottom:4px"><span class="endpoint-method '+methodClass+'">'+method+'</span><code style="font-size:14px;font-weight:600">'+esc(name)+'</code></div><p style="color:var(--text-secondary);font-size:13px">'+esc(desc)+'</p></div>'});$('endpointsList').innerHTML=html}
async function loadKeys(){if(!currentUser)return;var d=await api('dev.listKeys',{email:currentUser.email});if(d&&d.success&&d.keys){allKeys=d.keys;renderKeys(d.keys)}else{allKeys=[];renderKeys([])}}
function renderKeys(keys){var total=0,active=0,inactive=0,removed=0;keys.forEach(function(k){total++;if(k.status==='active')active++;else if(k.status==='inactive')inactive++;else if(k.status==='removed')removed++});$('statTotal').textContent=total;$('statActive').textContent=active;$('statInactive').textContent=inactive;$('statRemoved').textContent=removed;if(keys.length===0){$('keysTableContainer').innerHTML='<div style="text-align:center;padding:40px;color:var(--text-muted)"><p style="font-size:16px;margin-bottom:8px">No API keys yet</p><p style="font-size:13px">Create your first key to get started.</p></div>';return}var html='<div class="table-wrap"><table><thead><tr><th>Key</th><th>Name</th><th>Status</th><th>Created</th><th>Last Used</th><th>Requests</th><th style="width:160px">Actions</th></tr></thead><tbody>';keys.forEach(function(k){var keyStr=k.key||k.apiKey||'';var name=k.name||k.Name||'—';var status=k.status||k.Status||'active';var created=k.createdAt||k.CreatedAt||'—';var lastUsed=k.lastUsed||k.LastUsed||'—';var requests=k.requestCount||k.RequestCount||0;var statusClass=status==='active'?'active':status==='inactive'?'inactive':'removed';html+='<tr><td><span class="key-tag">'+esc(keyStr.substring(0,20))+'...</span></td><td>'+esc(name)+'</td><td><span class="status-badge '+statusClass+'">'+esc(status.charAt(0).toUpperCase()+status.slice(1))+'</span></td><td style="white-space:nowrap">'+esc(created)+'</td><td style="white-space:nowrap">'+esc(lastUsed)+'</td><td>'+requests+'</td><td style="white-space:nowrap"><button class="btn btn-sm btn-ghost key-action" data-action="copy" data-key="'+esc(keyStr)+'">Copy</button>'+(status==='active'?'<button class="btn btn-sm btn-ghost key-action" data-action="revoke" data-key="'+esc(keyStr)+'" style="color:var(--warning)">Revoke</button>':'')+(status==='inactive'?'<button class="btn btn-sm btn-ghost key-action" data-action="reactivate" data-key="'+esc(keyStr)+'" style="color:var(--success)">Activate</button>':'')+'<button class="btn btn-sm btn-ghost key-action" data-action="delete" data-key="'+esc(keyStr)+'" style="color:var(--danger)">Delete</button></td></tr>'});html+='</tbody></table></div>';$('keysTableContainer').innerHTML=html;$('keysTableContainer').querySelectorAll('.key-action').forEach(function(btn){btn.addEventListener('click',function(){var action=this.dataset.action;var keyVal=this.dataset.key;handleKeyAction(action,keyVal)})})}
function handleKeyAction(action,keyVal){if(action==='copy'){navigator.clipboard.writeText(keyVal).then(function(){Toast('success','Key copied')}).catch(function(){Toast('error','Failed to copy')})}if(action==='delete'){if(!confirm('Permanently delete this key?'))return;api('dev.deleteKey',{key:keyVal,email:currentUser.email}).then(function(d){if(d&&d.success){Toast('success','Key deleted');loadKeys()}else Toast('error',d&&d.message?d.message:'Delete failed')})}if(action==='revoke'){api('dev.revokeKey',{key:keyVal,email:currentUser.email}).then(function(d){if(d&&d.success){Toast('warning','Key revoked');loadKeys()}else Toast('error',d&&d.message?d.message:'Revoke failed')})}if(action==='reactivate'){api('dev.reactivateKey',{key:keyVal,email:currentUser.email}).then(function(d){if(d&&d.success){Toast('success','Key reactivated');loadKeys()}else Toast('error',d&&d.message?d.message:'Reactivation failed')})}}
async function createNewKey(){var name=$('newKeyName').value.trim()||'My API Key';var d=await api('dev.registerKey',{name:name,email:currentUser.email});if(d&&d.success&&d.key){$('newKeyName').value='';$('keyResult').style.display='';$('newKeyDisplay').textContent=d.key;$('createKeyConfirm').style.display='none';Toast('success','Key generated');loadKeys()}else{Toast('error',d&&d.message?d.message:'Key generation failed')}}
document.addEventListener('DOMContentLoaded',function(){EA_TRACKER.init('/developer/');var savedUser=EA_AUTH.getUser();if(savedUser){currentUser=savedUser;updateDevAuthUI()}else{show($('loginwall'));hideGlobalLoader()}auditEvent('pageview','/developer/');setInterval(function(){api('heartbeat',{user:currentUser?currentUser.email:''}).catch(function(e){console.error('Heartbeat failed:',e)})},60000);
var scrollDepth=0;window.addEventListener('scroll',function(){var d=Math.round((window.scrollY+window.innerHeight)/document.documentElement.scrollHeight*100);if(d>scrollDepth+10){scrollDepth=d;auditEvent('scroll',d+'%')}});
qsa('.auth-tab').forEach(function(t){t.addEventListener('click',function(){switchAuthTab(this.dataset.tab)})});
$('loginForm').addEventListener('submit',function(e){e.preventDefault();login($('loginEmail').value.trim(),$('loginPassword').value)});
$('registerForm').addEventListener('submit',function(e){e.preventDefault();var n=$('regName').value.trim();var em=$('regEmail').value.trim();var pw=$('regPassword').value;if(!n||!em||!pw)return Toast('error','Fill in all fields');if(pw.length<8)return Toast('error','Password must be 8+');register(n,em,pw)});
$('logoutBtn').addEventListener('click',logoutUser);
$('dropdownLogout').addEventListener('click',logoutUser);
$('userAvatarBtn').addEventListener('click',function(e){e.stopPropagation();var dd=$('userDropdown');dd.classList.toggle('hidden');if(!dd.classList.contains('hidden')){setTimeout(function(){document.addEventListener('click',function closeDd(){dd.classList.add('hidden');document.removeEventListener('click',closeDd)})},100)}});
qsa('#devTabs .tab').forEach(function(t){t.addEventListener('click',function(){switchDevTab(this.dataset.tab)})});
$('createKeyBtn').addEventListener('click',function(){$('keyResult').style.display='none';$('createKeyConfirm').style.display='';$('newKeyName').value='';$('createKeyModal').classList.remove('hidden')});
$('createKeyConfirm').addEventListener('click',createNewKey);
$('copyKeyBtn').addEventListener('click',function(){navigator.clipboard.writeText($('newKeyDisplay').textContent).then(function(){Toast('success','Copied')}).catch(function(){Toast('error','Failed')})});
$('keyDoneBtn').addEventListener('click',function(){$('createKeyModal').classList.add('hidden')});
$('refreshKeysBtn').addEventListener('click',function(){loadKeys();Toast('info','Keys refreshed')});
document.addEventListener('click',function(e){auditEvent('click',e.target.tagName+':'+(e.target.textContent||'').trim().slice(0,50))});
});
