var EA_API='https://script.google.com/macros/s/AKfycbyfr1k04IqvPSHND5I47ZowM8EAUmBuFR4pKJVWDdsB0ZCr4pMrCLxFME1v70aLbyWo/exec';
var EA_TRACKER={API_URL:EA_API,initialized:false,init:function(page){if(this.initialized)return;this.initialized=true;this.page=page||window.location.pathname;this.fingerprint=this.getFingerprint();var self=this;this.getIP().then(function(ip){self.ip=ip;self.send()});this.send()},getFingerprint:function(){var c=document.createElement('canvas');c.width=200;c.height=50;var t=c.getContext('2d');t.textBaseline='top';t.font='14px Arial';t.fillStyle='#f60';t.fillRect(125,1,62,20);t.fillStyle='#069';t.fillText('EA'+navigator.userAgent.length,2,15);t.fillStyle='rgba(102,204,0,0.7)';t.fillText('ExpressAirways',4,17);var n=c.toDataURL();var r='';try{var gl=document.createElement('canvas').getContext('webgl');if(gl){var ext=gl.getExtension('WEBGL_debug_renderer_info');if(ext)r=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)+'|'+gl.getParameter(ext.UNMASKED_VENDOR_WEBGL)}}catch(e){}var a=window.screen.width+'x'+window.screen.height+'x'+window.screen.colorDepth;var tz=Intl.DateTimeFormat().resolvedOptions().timeZone;var lang=navigator.language;var ua=navigator.userAgent;var s=[n,r,a,tz,lang,ua].join('|||');var h=0;for(var i=0;i<s.length;i++){var c2=s.charCodeAt(i);h=(h<<5)-h+c2;h|=0}return Math.abs(h).toString(16)},getIP:function(){return fetch('https://api.ipify.org?format=json',{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){return d.ip}).catch(function(){return''})},send:function(){var params={action:'audit.event',event:'pageview',page:this.page,fingerprint:this.fingerprint,ip:this.ip,ua:navigator.userAgent,screen:window.screen.width+'x'+window.screen.height,tz:Intl.DateTimeFormat().resolvedOptions().timeZone,lang:navigator.language};var qs=Object.entries(params).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');fetch(EA_API+'?'+qs+'&t='+Date.now(),{mode:'no-cors'}).catch(function(){})}};
var EA_AUTH={KEY:'ea_session',getUser:function(){try{var raw=localStorage.getItem(this.KEY);if(!raw)return null;var data=JSON.parse(raw);if(data&&data.user&&data.expires>Date.now())return data.user;if(data&&data.user)localStorage.removeItem(this.KEY);return null}catch(e){return null}},setUser:function(user){if(!user){localStorage.removeItem(this.KEY);return}var data={user:user,expires:Date.now()+604800000};localStorage.setItem(this.KEY,JSON.stringify(data))},logout:function(){localStorage.removeItem(this.KEY);this._notify(null)},_listeners:[],onChange:function(fn){this._listeners.push(fn)},_notify:function(user){for(var i=0;i<this._listeners.length;i++){try{this._listeners[i](user)}catch(e){}}}};
window.addEventListener('storage',function(e){if(e.key===EA_AUTH.KEY){try{var data=JSON.parse(e.newValue);EA_AUTH._notify(data?data.user:null)}catch(ex){EA_AUTH._notify(null)}}});
function Toast(type,message){var container=document.getElementById('toastContainer');if(!container)return;var icons={success:'\u2713',error:'\u2715',warning:'\u26A0',info:'\u2139'};var t=document.createElement('div');t.className='toast '+type;t.innerHTML='<span>'+(icons[type]||'')+'</span><span>'+message+'</span>';container.appendChild(t);var dur=type==='error'?10000:type==='success'?8000:6000;setTimeout(function(){t.style.animation='toastOut 0.3s ease forwards';setTimeout(function(){t.remove()},300)},dur)}
function $(id){return document.getElementById(id)}
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function show(el){if(el)el.classList.remove('hidden')}
function hide(el){if(el)el.classList.add('hidden')}
function qs(s){return document.querySelector(s)}
function qsa(s){return document.querySelectorAll(s)}
function btnLoading(el){if(!el)return;if(el.dataset._orig===undefined)el.dataset._orig=el.innerHTML;el.classList.add('loading');el.disabled=true}
function btnReset(el){if(!el)return;el.classList.remove('loading');el.disabled=false}
async function api(action,extra){var p={action:action};if(extra)for(var k in extra)p[k]=extra[k];var qs2=Object.entries(p).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');try{var c=new AbortController();var t=setTimeout(function(){c.abort()},15000);var r=await fetch(EA_API+'?'+qs2+'&t='+Date.now(),{cache:'no-store',signal:c.signal});clearTimeout(t);return await r.json()}catch(e){console.error('EA API Error:',e);return null}}
function auditEvent(eventType,detail){try{var params={action:'audit.event',event:eventType,page:window.location.pathname,fingerprint:EA_TRACKER.fingerprint,detail:detail||'',user:currentUser?currentUser.email:''};var qs3=Object.entries(params).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');fetch(EA_API+'?'+qs3+'&t='+Date.now(),{mode:'no-cors'}).catch(function(e){console.error('Audit failed:',e)})}catch(e){console.error('Audit error:',e)}}
var currentUser=null;
function updateAuthUI(){if(currentUser){hide($('loginwall'));show($('userMenu'));show($('logoutBtn'));$('avatarInitials').textContent=(currentUser.name||'U').split(' ').map(function(w){return w[0]}).join('').toUpperCase().slice(0,2);$('dropdownName').textContent=currentUser.name||'User';$('dropdownEmail').textContent=currentUser.email||'';$('profileAvatar').textContent=(currentUser.name||'U').split(' ').map(function(w){return w[0]}).join('').toUpperCase().slice(0,2);$('profileName').textContent='Welcome, '+(currentUser.name||'')+'!';$('profileEmail').textContent=currentUser.email||'';$('detailName').textContent=currentUser.name||'—';$('detailEmail').textContent=currentUser.email||'—';$('detailJoined').textContent=currentUser.joinDate||currentUser.JoinDate||'—';$('detailRole').textContent=currentUser.role||currentUser.Role||'Member';$('editName').value=currentUser.name||'';$('editEmail').value=currentUser.email||'';loadUserData()}else{show($('loginwall'));hide($('userMenu'));hide($('logoutBtn'))}}
async function login(email,password){btnLoading(qs('#loginForm button[type="submit"]'));var d=await api('login',{email:email,password:password});btnReset(qs('#loginForm button[type="submit"]'));if(d&&d.success){currentUser=d.user;EA_AUTH.setUser(d.user);updateAuthUI();Toast('success','Welcome back, '+d.user.name+'!');auditEvent('login',email)}else{Toast('error',d&&d.message?d.message:'Login failed')}}
async function register(name,email,password){btnLoading(qs('#registerForm button[type="submit"]'));var d=await api('signup',{fullName:name,email:email,password:password});btnReset(qs('#registerForm button[type="submit"]'));if(d&&d.success){Toast('success','Account created! Please sign in.');switchAuthTab('login')}else{Toast('error',d&&d.message?d.message:'Registration failed')}}
function logoutUser(){currentUser=null;EA_AUTH.logout();updateAuthUI();Toast('info','Signed out');auditEvent('logout','')}
function switchAuthTab(tab){qsa('.auth-tab').forEach(function(t){t.classList.toggle('active',t.dataset.tab===tab)});hide($('loginForm'));hide($('registerForm'));show(tab==='login'?$('loginForm'):$('registerForm'))}
function switchTab(tab){qsa('#accountTabs .tab').forEach(function(t){t.classList.toggle('active',t.dataset.tab===tab)});hide($('tabProfile'));hide($('tabBookings'));hide($('tabMiles'));hide($('tabSettings'));show($('tab'+tab.charAt(0).toUpperCase()+tab.slice(1)));auditEvent('tab_switch',tab)}
async function loadUserData(){var email=currentUser.email||currentUser.Email;if(!email)return;var d=await api('getUser',{email:email});if(d&&d.success&&d.user){var u=d.user;$('milesBalanceDisplay').textContent=(u.miles||0).toLocaleString();$('milesTotal').textContent=(u.miles||0).toLocaleString();$('milesEarnedYear').textContent=(u.milesEarnedYear||u.yearlyMiles||0).toLocaleString();$('milesRedeemed').textContent=(u.milesRedeemed||u.redeemedMiles||0).toLocaleString();var tier=u.loyaltyTier||u.LoyaltyTier||'Basic';var tierEl=$('tierDisplay');tierEl.textContent=tier;tierEl.className='tier-badge tier-'+tier.toLowerCase();currentUser.miles=u.miles;currentUser.loyaltyTier=tier}var b=await api('getUserBookings',{email:email});if(b&&b.success&&b.bookings&&b.bookings.length>0){var html='<div class="table-wrap"><table><thead><tr><th>Ref</th><th>Route</th><th>Date</th><th>Status</th><th>Total</th></tr></thead><tbody>';b.bookings.forEach(function(bk){html+='<tr><td>'+esc(bk.BookingRef||bk.bookingRef||'')+'</td><td>'+esc((bk.Origin||'')+' \u2192 '+(bk.Destination||''))+'</td><td>'+esc(bk.DepartDate||bk.departDate||'')+'</td><td>'+esc(bk.Status||bk.status||'')+'</td><td>'+(bk.TotalPrice||bk.totalPrice||'')+'</td></tr>'});html+='</tbody></table></div>';$('bookingsContainer').innerHTML=html}else{$('bookingsContainer').innerHTML='<p style="color:var(--text-muted);text-align:center;padding:20px">No bookings found.</p>'}}
document.addEventListener('DOMContentLoaded',function(){EA_TRACKER.init('/account/');var savedUser=EA_AUTH.getUser();if(savedUser){currentUser=savedUser;updateAuthUI()}else{show($('loginwall'));hideGlobalLoader()}auditEvent('pageview','/account/');setInterval(function(){api('heartbeat',{user:currentUser?currentUser.email:''}).catch(function(e){console.error('Heartbeat failed:',e)})},60000);
var scrollDepth=0;window.addEventListener('scroll',function(){var d=Math.round((window.scrollY+window.innerHeight)/document.documentElement.scrollHeight*100);if(d>scrollDepth+10){scrollDepth=d;auditEvent('scroll',d+'%')}});
qsa('.auth-tab').forEach(function(t){t.addEventListener('click',function(){switchAuthTab(this.dataset.tab)})});
$('loginForm').addEventListener('submit',function(e){e.preventDefault();login($('loginEmail').value.trim(),$('loginPassword').value)});
$('registerForm').addEventListener('submit',function(e){e.preventDefault();var n=$('regName').value.trim();var em=$('regEmail').value.trim();var pw=$('regPassword').value;if(!n||!em||!pw)return Toast('error','Fill in all fields');if(pw.length<8)return Toast('error','Password must be 8+ characters');register(n,em,pw)});
$('logoutBtn').addEventListener('click',logoutUser);
$('dropdownLogout').addEventListener('click',logoutUser);
$('dropdownProfile').addEventListener('click',function(){switchTab('profile')});
$('dropdownBookings').addEventListener('click',function(){switchTab('bookings')});
$('dropdownMiles').addEventListener('click',function(){switchTab('miles')});
qsa('#accountTabs .tab').forEach(function(t){t.addEventListener('click',function(){switchTab(this.dataset.tab)})});
$('userAvatarBtn').addEventListener('click',function(e){e.stopPropagation();var dd=$('userDropdown');dd.classList.toggle('hidden');if(!dd.classList.contains('hidden')){setTimeout(function(){document.addEventListener('click',function closeDd(){dd.classList.add('hidden');document.removeEventListener('click',closeDd)})},100)}});
$('editProfileForm').addEventListener('submit',async function(e){e.preventDefault();var name=$('editName').value.trim();if(!name)return Toast('error','Name required');btnLoading(qs('#editProfileForm button[type="submit"]'));var d=await api('admin.updateUser',{email:currentUser.email,fullName:name});btnReset(qs('#editProfileForm button[type="submit"]'));if(d&&d.success){currentUser.name=name;EA_AUTH.setUser(currentUser);updateAuthUI();Toast('success','Profile updated');auditEvent('profile_update',name)}else{Toast('error',d&&d.message?d.message:'Update failed')}});
$('saveNotifBtn').addEventListener('click',function(){var prefs={bookings:$('notifBookings').checked,promos:$('notifPromos').checked,status:$('notifStatus').checked,miles:$('notifMiles').checked};Toast('success','Notification preferences saved');auditEvent('notif_prefs',JSON.stringify(prefs))});
document.addEventListener('click',function(e){auditEvent('click',e.target.tagName+':'+(e.target.textContent||'').trim().slice(0,50))});
});
