var EA_API='https://script.google.com/macros/s/AKfycbybXfKdhOFdXIOa2RTaF5YHeFWKYt6IU2_F87IH1LzvIzhU7UVEd4aVmK8_vKuAlBVp/exec';
var EA_TRACKER={API_URL:EA_API,initialized:false,init:function(page){if(this.initialized)return;this.initialized=true;this.page=page||window.location.pathname;this.fingerprint=this.getFingerprint();var self=this;this.getIP().then(function(ip){self.ip=ip;self.send()});this.send()},getFingerprint:function(){var c=document.createElement('canvas');c.width=200;c.height=50;var t=c.getContext('2d');t.textBaseline='top';t.font='14px Arial';t.fillStyle='#f60';t.fillRect(125,1,62,20);t.fillStyle='#069';t.fillText('EA'+navigator.userAgent.length,2,15);t.fillStyle='rgba(102,204,0,0.7)';t.fillText('ExpressAirways',4,17);var n=c.toDataURL();var r='';try{var gl=document.createElement('canvas').getContext('webgl');if(gl){var ext=gl.getExtension('WEBGL_debug_renderer_info');if(ext)r=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)+'|'+gl.getParameter(ext.UNMASKED_VENDOR_WEBGL)}}catch(e){}var a=window.screen.width+'x'+window.screen.height+'x'+window.screen.colorDepth;var tz=Intl.DateTimeFormat().resolvedOptions().timeZone;var lang=navigator.language;var ua=navigator.userAgent;var s=[n,r,a,tz,lang,ua].join('|||');var h=0;for(var i=0;i<s.length;i++){var c2=s.charCodeAt(i);h=(h<<5)-h+c2;h|=0}return Math.abs(h).toString(16)},getIP:function(){return fetch('https://api.ipify.org?format=json',{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){return d.ip}).catch(function(){return''})},send:function(){var params={action:'audit.event',event:'pageview',page:this.page,fingerprint:this.fingerprint,ip:this.ip,ua:navigator.userAgent,screen:window.screen.width+'x'+window.screen.height,tz:Intl.DateTimeFormat().resolvedOptions().timeZone,lang:navigator.language};var qs=Object.entries(params).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');fetch(EA_API+'?'+qs+'&t='+Date.now(),{mode:'no-cors'}).catch(function(){})}};
var EA_AUTH={KEY:'ea_session',getUser:function(){try{var raw=localStorage.getItem(this.KEY);if(!raw)return null;var data=JSON.parse(raw);if(data&&data.user&&data.expires>Date.now())return data.user;if(data&&data.user)localStorage.removeItem(this.KEY);return null}catch(e){return null}},setUser:function(user){if(!user){localStorage.removeItem(this.KEY);return}var data={user:user,expires:Date.now()+604800000};localStorage.setItem(this.KEY,JSON.stringify(data))},logout:function(){localStorage.removeItem(this.KEY);this._notify(null)},_listeners:[],onChange:function(fn){this._listeners.push(fn)},_notify:function(user){for(var i=0;i<this._listeners.length;i++){try{this._listeners[i](user)}catch(e){}}}};
window.addEventListener('storage',function(e){if(e.key===EA_AUTH.KEY){try{var data=JSON.parse(e.newValue);EA_AUTH._notify(data?data.user:null)}catch(ex){EA_AUTH._notify(null)}}});
function Toast(type,message){var container=document.getElementById('toastContainer');if(!container)return;var icons={success:'\u2713',error:'\u2715',warning:'\u26A0',info:'\u2139'};var t=document.createElement('div');t.className='toast '+type;t.innerHTML='<span>'+(icons[type]||'')+'</span><span>'+message+'</span>';container.appendChild(t);var dur=type==='error'?10000:type==='success'?8000:6000;setTimeout(function(){t.style.animation='toastOut 0.3s ease forwards';setTimeout(function(){t.remove()},300)},dur)}
function $(id){return document.getElementById(id)}
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function show(el){if(el)el.classList.remove('hidden')}
function hide(el){if(el)el.classList.add('hidden')}
function qs(s){return document.querySelector(s)}
function qsa(s){return document.querySelectorAll(s)}
function btnLoading(el){if(!el)return;if(el.dataset._orig===undefined)el.dataset._orig=el.innerHTML;el.classList.add('loading');el.disabled=true}
function btnReset(el){if(!el)return;el.classList.remove('loading');el.disabled=false}
async function api(method,params){var p={};if(params)for(var k in params)p[k]=params[k];var qs2=Object.entries(p).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');try{var c=new AbortController();var t=setTimeout(function(){c.abort()},15000);var r=await fetch(EA_API+'?'+qs2+'&t='+Date.now(),{cache:'no-store',signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}catch(e){console.error('EA API Error:',e);return null}}
function auditEvent(eventType,detail){try{var params={action:'audit.event',event:eventType,page:window.location.pathname,fingerprint:EA_TRACKER.fingerprint,detail:detail||'',user:currentUser?currentUser.email:''};var qs3=Object.entries(params).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1]||'')}).join('&');fetch(EA_API+'?'+qs3+'&t='+Date.now(),{mode:'no-cors'}).catch(function(e){console.error('Audit failed:',e)})}catch(e){console.error('Audit error:',e)}}
var currentUser=null;
var state={currentAdminTab:'dashboard',allData:{},searchQuery:'',tableData:[]};
var ADMIN_TABLES=['Users','Bookings','Sections','Events','Documents','PromoCodes','Notices','Config','SystemStatus','Ancillaries','Contact','Issues','DocRequests','Notifications','Cases','Participants','Evidence','Verdicts','Reviews','Referrals'];
var TABLE_COLS={Users:["UserID","FullName","Email","Password","Role","Miles","Status","JoinDate"],Bookings:["BookingRef","Email","Status","Origin","Destination","DepartDate","ServiceType","Passengers","TotalPrice","PaxCabin"],Sections:["Title","Description","Image","Link"],Events:["Date","Title","Description","Image"],Documents:["ID","Title","Description","Type","Category"],PromoCodes:["Code","DiscountPercent","MaxUses","UsedCount","ExpiryDate","Active"],Config:["Key","Value"],SystemStatus:["Key","Value"],Ancillaries:["Type","Description","Price"],Contact:["Name","Email","Message","Timestamp"],Issues:["IssueID","Email","Subject","Severity","Status"],DocRequests:["UserEmail","DocTitle","Reason","Status"],Notifications:["NotificationID","Email","Type","Title","Read","CreatedAt"],Cases:["CaseID","Title","Type","Status"],Participants:["ParticipantID","CaseID","Email","Role"],Evidence:["EvidenceID","CaseID","Type","Title"],Verdicts:["VerdictID","CaseID","Outcome","SubmittedBy"],Reviews:["BookingRef","Email","Rating","Comment"],Referrals:["ReferrerEmail","RefereeEmail","Status"]};
function updateAdminUI(){if(currentUser&&(currentUser.role==='Admin'||currentUser.role==='Administrator')){hide($('loginwall'));show($('adminApp'));show($('userMenu'));show($('logoutBtn'));$('avatarInitials').textContent=(currentUser.name||'A').charAt(0).toUpperCase();$('dropdownName').textContent=currentUser.name||'Admin';$('dropdownEmail').textContent=currentUser.email||'';loadAdminDashboard()}else{show($('loginwall'));hide($('adminApp'));hide($('userMenu'));hide($('logoutBtn'))}}
async function adminLogin(email,password){btnLoading(qs('#adminLoginForm button[type="submit"]'));var d=await api('admin.login',{email:email,password:password});btnReset(qs('#adminLoginForm button[type="submit"]'));if(d&&d.success){currentUser=d.user;EA_AUTH.setUser(d.user);updateAdminUI();Toast('success','Welcome, '+d.user.name);auditEvent('admin_login',email)}else{Toast('error',d&&d.message?d.message:'Login failed')}}
function adminLogout(){currentUser=null;EA_AUTH.logout();updateAdminUI();Toast('info','Signed out');auditEvent('admin_logout','')}
async function loadAdminDashboard(){var d=await api('admin.getAllTables',{});if(d&&d.success){state.allData=d.tables||{};renderAdminStats();renderSidebar()}else{state.allData={}}switchAdminTab(state.currentAdminTab)}
function renderAdminStats(){var grid=$('statsGrid');if(!grid)return;var counts={};for(var key in state.allData){if(Array.isArray(state.allData[key]))counts[key]=state.allData[key].length}var top=['Users','Bookings','Documents','Issues','Contact','Config','Events','Cases'];grid.innerHTML=top.map(function(k){return'<div class="admin-stat-card"><div class="admin-stat-number">'+(counts[k]||0)+'</div><div class="admin-stat-label">'+k+'</div></div>'}).join('')}
function renderSidebar(){var nav=$('sidebarNav');if(!nav)return;nav.innerHTML='';ADMIN_TABLES.forEach(function(name){var item=document.createElement('button');item.className='admin-sidebar-item';item.dataset.table=name;item.innerHTML='<span>&#x1F4C1;</span><span>'+name+'</span>';item.addEventListener('click',function(){switchAdminTab('table');loadTable(name)});nav.appendChild(item)})}
function switchAdminTab(tab){state.currentAdminTab=tab;qsa('.admin-tab').forEach(function(t){t.classList.toggle('active',t.dataset.section===tab)});hide($('sectionDashboard'));hide($('sectionUsers'));hide($('sectionBookings'));hide($('sectionAudit'));hide($('sectionConfig'));if(tab==='dashboard'){show($('sectionDashboard'));$('sectionTitle').textContent='Dashboard';$('sectionSubtitle').textContent='System overview';$('addRowBtn').style.display='none';renderAdminDashboard()}else if(tab==='users'){show($('sectionUsers'));$('sectionTitle').textContent='User Management';$('sectionSubtitle').textContent='Manage all registered users';$('addRowBtn').style.display='';renderUsersTable()}else if(tab==='bookings'){show($('sectionBookings'));$('sectionTitle').textContent='All Bookings';$('sectionSubtitle').textContent='Manage all flight bookings';$('addRowBtn').style.display='';renderBookingsTable()}else if(tab==='audit'){show($('sectionAudit'));$('sectionTitle').textContent='Audit Log';$('sectionSubtitle').textContent='System activity and audit trail';$('addRowBtn').style.display='none';renderAuditTable()}else if(tab==='config'){show($('sectionConfig'));$('sectionTitle').textContent='System Configuration';$('sectionSubtitle').textContent='Key-value configuration settings';$('addRowBtn').style.display='';renderConfigTable()}}
async function renderAdminDashboard(){var d=await api('getStats',{});if(d&&d.success){var usersData=state.allData.Users||[];var bookingsData=state.allData.Bookings||[];var docsData=state.allData.Documents||[];var online=usersData.filter(function(u){return u.Status==='online'||u.Status==='active'}).length||0;var html='<div class="admin-stats" style="grid-template-columns:repeat(4,1fr)"><div class="admin-stat-card"><div class="admin-stat-number">'+(d.totalUsers||usersData.length||0)+'</div><div class="admin-stat-label">Total Users</div></div><div class="admin-stat-card"><div class="admin-stat-number">'+(d.totalBookings||bookingsData.length||0)+'</div><div class="admin-stat-label">Total Bookings</div></div><div class="admin-stat-card"><div class="admin-stat-number">'+(d.totalDocuments||docsData.length||0)+'</div><div class="admin-stat-label">Documents</div></div><div class="admin-stat-card"><div class="admin-stat-number">'+online+'</div><div class="admin-stat-label">Users Online</div></div></div>';$('sectionDashboard').innerHTML=html}}
async function renderUsersTable(){var rows=state.allData.Users||[];if(rows.length===0){var d=await api('getAllUsers',{});if(d&&d.success)rows=d.users||[];state.allData.Users=rows}renderGenericTable('Users',rows,$('sectionUsers'))}
async function renderBookingsTable(){var rows=state.allData.Bookings||[];if(rows.length===0){var d=await api('getAllBookings',{});if(d&&d.success)rows=d.bookings||[];state.allData.Bookings=rows}renderGenericTable('Bookings',rows,$('sectionBookings'))}
async function renderAuditTable(){var d=await api('fetchAudit',{});var rows=(d&&d.success&&d.audit)?d.audit:[];var cols=['Timestamp','User','Action','Details','CaseID'];var html='<div class="data-table-wrap"><table class="data-table"><thead><tr>';cols.forEach(function(c){html+='<th>'+esc(c)+'</th>'});html+='</tr></thead><tbody>';if(rows.length===0){html+='<tr><td colspan="'+cols.length+'" style="text-align:center;color:var(--text-muted)">No audit entries</td></tr>'}else{rows.forEach(function(r){html+='<tr>';cols.forEach(function(c){var key=c.charAt(0).toLowerCase()+c.slice(1);var val=r[key]||r[c]||'—';if(String(val).length>50)val=String(val).slice(0,50)+'...';html+='<td>'+esc(String(val))+'</td>'});html+='</tr>'})}html+='</tbody></table></div>';$('sectionAudit').innerHTML=html}
async function renderConfigTable(){var d=await api('getConfig',{});var rows=(d&&d.success&&d.config)?d.config:[];var html='<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Key</th><th>Value</th><th style="width:120px">Actions</th></tr></thead><tbody>';if(rows.length===0){html+='<tr><td colspan="3" style="text-align:center;color:var(--text-muted)">No configuration</td></tr>'}else{rows.forEach(function(r,i){var key=r.Key||r.key||'—';var val=r.Value||r.value||'—';html+='<tr><td>'+esc(String(key))+'</td><td>'+esc(String(val))+'</td><td class="actions-cell"><button class="btn btn-sm btn-ghost" onclick="editConfig(\''+esc(String(key))+'\',\''+esc(String(val))+'\')">Edit</button><button class="btn btn-sm btn-ghost" style="color:var(--danger)" onclick="deleteConfig(\''+esc(String(key))+'\')">Delete</button></td></tr>'})}html+='</tbody></table></div>';$('sectionConfig').innerHTML=html}
function renderGenericTable(name,rows,container){var cols=TABLE_COLS[name]||Object.keys(rows[0]||{});var html='<div class="data-table-wrap"><table class="data-table"><thead><tr>';cols.forEach(function(c){html+='<th>'+esc(c)+'</th>'});html+='<th style="width:120px">Actions</th></tr></thead><tbody>';if(rows.length===0){html+='<tr><td colspan="'+(cols.length+1)+'" style="text-align:center;padding:40px;color:var(--text-muted)">No data</td></tr>'}else{rows.forEach(function(row,idx){html+='<tr>';cols.forEach(function(c){var val=row[c]!==undefined&&row[c]!==null?String(row[c]):'';if(val.length>40)val=val.slice(0,40)+'...';html+='<td title="'+esc(row[c]||'')+'">'+esc(val)+'</td>'});html+='<td class="actions-cell"><button class="btn btn-sm btn-ghost" onclick="editRow(\''+esc(name)+'\','+idx+')">Edit</button><button class="btn btn-sm btn-ghost" style="color:var(--danger)" onclick="deleteRow(\''+esc(name)+'\','+idx+')">Delete</button></td></tr>'})}html+='</tbody></table></div>';container.innerHTML=html}
function loadTable(name){switchAdminTab('table');var container;if(name==='Users'){container=$('sectionUsers');show($('sectionUsers'))}else if(name==='Bookings'){container=$('sectionBookings');show($('sectionBookings'))}else{container=document.createElement('div');container.id='dynamicTable';var existing=$('dynamicTable');if(existing)existing.remove();$('adminTabs').after(container);show(container)}$('sectionTitle').textContent=name;$('sectionSubtitle').textContent='Viewing '+name+' table';$('addRowBtn').style.display='';var rows=state.allData[name]||[];renderGenericTable(name,rows,container)}
document.addEventListener('DOMContentLoaded',function(){EA_TRACKER.init('/admin/');var savedUser=EA_AUTH.getUser();if(savedUser&&(savedUser.role==='Admin'||savedUser.role==='Administrator')){currentUser=savedUser;updateAdminUI()}else{show($('loginwall'));hideGlobalLoader()}auditEvent('pageview','/admin/');setInterval(function(){api('heartbeat',{user:currentUser?currentUser.email:''}).catch(function(e){console.error('Heartbeat failed:',e)})},60000);
var scrollDepth=0;window.addEventListener('scroll',function(){var d=Math.round((window.scrollY+window.innerHeight)/document.documentElement.scrollHeight*100);if(d>scrollDepth+10){scrollDepth=d;auditEvent('scroll',d+'%')}});
$('adminLoginForm').addEventListener('submit',function(e){e.preventDefault();adminLogin($('loginEmail').value.trim(),$('loginPassword').value)});
$('logoutBtn').addEventListener('click',adminLogout);
$('dropdownLogout').addEventListener('click',adminLogout);
$('userAvatarBtn').addEventListener('click',function(e){e.stopPropagation();var dd=$('userDropdown');dd.classList.toggle('hidden');if(!dd.classList.contains('hidden')){setTimeout(function(){document.addEventListener('click',function closeDd(){dd.classList.add('hidden');document.removeEventListener('click',closeDd)})},100)}});
qsa('.admin-tab').forEach(function(t){t.addEventListener('click',function(){switchAdminTab(this.dataset.section)})});
$('refreshBtn').addEventListener('click',function(){loadAdminDashboard();Toast('info','Data refreshed')});
document.addEventListener('click',function(e){auditEvent('click',e.target.tagName+':'+(e.target.textContent||'').trim().slice(0,50))});
});
